import * as mongodb from "mongodb";

test("测试 MongoDB", () => {
  const keys = Object.keys(mongodb);

  // expect(keys).toContains("MongoClient");

  expect(expect()).toMatchInlineSnapshot(`
    Object {
      "lastCalledWith": [Function],
      "lastReturnedWith": [Function],
      "not": Object {
        "lastCalledWith": [Function],
        "lastReturnedWith": [Function],
        "nthCalledWith": [Function],
        "nthReturnedWith": [Function],
        "toBe": [Function],
        "toBeCalled": [Function],
        "toBeCalledTimes": [Function],
        "toBeCalledWith": [Function],
        "toBeCloseTo": [Function],
        "toBeDefined": [Function],
        "toBeFalsy": [Function],
        "toBeGreaterThan": [Function],
        "toBeGreaterThanOrEqual": [Function],
        "toBeInstanceOf": [Function],
        "toBeLessThan": [Function],
        "toBeLessThanOrEqual": [Function],
        "toBeNaN": [Function],
        "toBeNull": [Function],
        "toBeTruthy": [Function],
        "toBeUndefined": [Function],
        "toContain": [Function],
        "toContainEqual": [Function],
        "toEqual": [Function],
        "toHaveBeenCalled": [Function],
        "toHaveBeenCalledTimes": [Function],
        "toHaveBeenCalledWith": [Function],
        "toHaveBeenLastCalledWith": [Function],
        "toHaveBeenNthCalledWith": [Function],
        "toHaveLastReturnedWith": [Function],
        "toHaveLength": [Function],
        "toHaveNthReturnedWith": [Function],
        "toHaveProperty": [Function],
        "toHaveReturned": [Function],
        "toHaveReturnedTimes": [Function],
        "toHaveReturnedWith": [Function],
        "toMatch": [Function],
        "toMatchInlineSnapshot": [Function],
        "toMatchObject": [Function],
        "toMatchSnapshot": [Function],
        "toReturn": [Function],
        "toReturnTimes": [Function],
        "toReturnWith": [Function],
        "toStrictEqual": [Function],
        "toThrow": [Function],
        "toThrowError": [Function],
        "toThrowErrorMatchingInlineSnapshot": [Function],
        "toThrowErrorMatchingSnapshot": [Function],
      },
      "nthCalledWith": [Function],
      "nthReturnedWith": [Function],
      "rejects": Object {
        "lastCalledWith": [Function],
        "lastReturnedWith": [Function],
        "not": Object {
          "lastCalledWith": [Function],
          "lastReturnedWith": [Function],
          "nthCalledWith": [Function],
          "nthReturnedWith": [Function],
          "toBe": [Function],
          "toBeCalled": [Function],
          "toBeCalledTimes": [Function],
          "toBeCalledWith": [Function],
          "toBeCloseTo": [Function],
          "toBeDefined": [Function],
          "toBeFalsy": [Function],
          "toBeGreaterThan": [Function],
          "toBeGreaterThanOrEqual": [Function],
          "toBeInstanceOf": [Function],
          "toBeLessThan": [Function],
          "toBeLessThanOrEqual": [Function],
          "toBeNaN": [Function],
          "toBeNull": [Function],
          "toBeTruthy": [Function],
          "toBeUndefined": [Function],
          "toContain": [Function],
          "toContainEqual": [Function],
          "toEqual": [Function],
          "toHaveBeenCalled": [Function],
          "toHaveBeenCalledTimes": [Function],
          "toHaveBeenCalledWith": [Function],
          "toHaveBeenLastCalledWith": [Function],
          "toHaveBeenNthCalledWith": [Function],
          "toHaveLastReturnedWith": [Function],
          "toHaveLength": [Function],
          "toHaveNthReturnedWith": [Function],
          "toHaveProperty": [Function],
          "toHaveReturned": [Function],
          "toHaveReturnedTimes": [Function],
          "toHaveReturnedWith": [Function],
          "toMatch": [Function],
          "toMatchInlineSnapshot": [Function],
          "toMatchObject": [Function],
          "toMatchSnapshot": [Function],
          "toReturn": [Function],
          "toReturnTimes": [Function],
          "toReturnWith": [Function],
          "toStrictEqual": [Function],
          "toThrow": [Function],
          "toThrowError": [Function],
          "toThrowErrorMatchingInlineSnapshot": [Function],
          "toThrowErrorMatchingSnapshot": [Function],
        },
        "nthCalledWith": [Function],
        "nthReturnedWith": [Function],
        "toBe": [Function],
        "toBeCalled": [Function],
        "toBeCalledTimes": [Function],
        "toBeCalledWith": [Function],
        "toBeCloseTo": [Function],
        "toBeDefined": [Function],
        "toBeFalsy": [Function],
        "toBeGreaterThan": [Function],
        "toBeGreaterThanOrEqual": [Function],
        "toBeInstanceOf": [Function],
        "toBeLessThan": [Function],
        "toBeLessThanOrEqual": [Function],
        "toBeNaN": [Function],
        "toBeNull": [Function],
        "toBeTruthy": [Function],
        "toBeUndefined": [Function],
        "toContain": [Function],
        "toContainEqual": [Function],
        "toEqual": [Function],
        "toHaveBeenCalled": [Function],
        "toHaveBeenCalledTimes": [Function],
        "toHaveBeenCalledWith": [Function],
        "toHaveBeenLastCalledWith": [Function],
        "toHaveBeenNthCalledWith": [Function],
        "toHaveLastReturnedWith": [Function],
        "toHaveLength": [Function],
        "toHaveNthReturnedWith": [Function],
        "toHaveProperty": [Function],
        "toHaveReturned": [Function],
        "toHaveReturnedTimes": [Function],
        "toHaveReturnedWith": [Function],
        "toMatch": [Function],
        "toMatchInlineSnapshot": [Function],
        "toMatchObject": [Function],
        "toMatchSnapshot": [Function],
        "toReturn": [Function],
        "toReturnTimes": [Function],
        "toReturnWith": [Function],
        "toStrictEqual": [Function],
        "toThrow": [Function],
        "toThrowError": [Function],
        "toThrowErrorMatchingInlineSnapshot": [Function],
        "toThrowErrorMatchingSnapshot": [Function],
      },
      "resolves": Object {
        "lastCalledWith": [Function],
        "lastReturnedWith": [Function],
        "not": Object {
          "lastCalledWith": [Function],
          "lastReturnedWith": [Function],
          "nthCalledWith": [Function],
          "nthReturnedWith": [Function],
          "toBe": [Function],
          "toBeCalled": [Function],
          "toBeCalledTimes": [Function],
          "toBeCalledWith": [Function],
          "toBeCloseTo": [Function],
          "toBeDefined": [Function],
          "toBeFalsy": [Function],
          "toBeGreaterThan": [Function],
          "toBeGreaterThanOrEqual": [Function],
          "toBeInstanceOf": [Function],
          "toBeLessThan": [Function],
          "toBeLessThanOrEqual": [Function],
          "toBeNaN": [Function],
          "toBeNull": [Function],
          "toBeTruthy": [Function],
          "toBeUndefined": [Function],
          "toContain": [Function],
          "toContainEqual": [Function],
          "toEqual": [Function],
          "toHaveBeenCalled": [Function],
          "toHaveBeenCalledTimes": [Function],
          "toHaveBeenCalledWith": [Function],
          "toHaveBeenLastCalledWith": [Function],
          "toHaveBeenNthCalledWith": [Function],
          "toHaveLastReturnedWith": [Function],
          "toHaveLength": [Function],
          "toHaveNthReturnedWith": [Function],
          "toHaveProperty": [Function],
          "toHaveReturned": [Function],
          "toHaveReturnedTimes": [Function],
          "toHaveReturnedWith": [Function],
          "toMatch": [Function],
          "toMatchInlineSnapshot": [Function],
          "toMatchObject": [Function],
          "toMatchSnapshot": [Function],
          "toReturn": [Function],
          "toReturnTimes": [Function],
          "toReturnWith": [Function],
          "toStrictEqual": [Function],
          "toThrow": [Function],
          "toThrowError": [Function],
          "toThrowErrorMatchingInlineSnapshot": [Function],
          "toThrowErrorMatchingSnapshot": [Function],
        },
        "nthCalledWith": [Function],
        "nthReturnedWith": [Function],
        "toBe": [Function],
        "toBeCalled": [Function],
        "toBeCalledTimes": [Function],
        "toBeCalledWith": [Function],
        "toBeCloseTo": [Function],
        "toBeDefined": [Function],
        "toBeFalsy": [Function],
        "toBeGreaterThan": [Function],
        "toBeGreaterThanOrEqual": [Function],
        "toBeInstanceOf": [Function],
        "toBeLessThan": [Function],
        "toBeLessThanOrEqual": [Function],
        "toBeNaN": [Function],
        "toBeNull": [Function],
        "toBeTruthy": [Function],
        "toBeUndefined": [Function],
        "toContain": [Function],
        "toContainEqual": [Function],
        "toEqual": [Function],
        "toHaveBeenCalled": [Function],
        "toHaveBeenCalledTimes": [Function],
        "toHaveBeenCalledWith": [Function],
        "toHaveBeenLastCalledWith": [Function],
        "toHaveBeenNthCalledWith": [Function],
        "toHaveLastReturnedWith": [Function],
        "toHaveLength": [Function],
        "toHaveNthReturnedWith": [Function],
        "toHaveProperty": [Function],
        "toHaveReturned": [Function],
        "toHaveReturnedTimes": [Function],
        "toHaveReturnedWith": [Function],
        "toMatch": [Function],
        "toMatchInlineSnapshot": [Function],
        "toMatchObject": [Function],
        "toMatchSnapshot": [Function],
        "toReturn": [Function],
        "toReturnTimes": [Function],
        "toReturnWith": [Function],
        "toStrictEqual": [Function],
        "toThrow": [Function],
        "toThrowError": [Function],
        "toThrowErrorMatchingInlineSnapshot": [Function],
        "toThrowErrorMatchingSnapshot": [Function],
      },
      "toBe": [Function],
      "toBeCalled": [Function],
      "toBeCalledTimes": [Function],
      "toBeCalledWith": [Function],
      "toBeCloseTo": [Function],
      "toBeDefined": [Function],
      "toBeFalsy": [Function],
      "toBeGreaterThan": [Function],
      "toBeGreaterThanOrEqual": [Function],
      "toBeInstanceOf": [Function],
      "toBeLessThan": [Function],
      "toBeLessThanOrEqual": [Function],
      "toBeNaN": [Function],
      "toBeNull": [Function],
      "toBeTruthy": [Function],
      "toBeUndefined": [Function],
      "toContain": [Function],
      "toContainEqual": [Function],
      "toEqual": [Function],
      "toHaveBeenCalled": [Function],
      "toHaveBeenCalledTimes": [Function],
      "toHaveBeenCalledWith": [Function],
      "toHaveBeenLastCalledWith": [Function],
      "toHaveBeenNthCalledWith": [Function],
      "toHaveLastReturnedWith": [Function],
      "toHaveLength": [Function],
      "toHaveNthReturnedWith": [Function],
      "toHaveProperty": [Function],
      "toHaveReturned": [Function],
      "toHaveReturnedTimes": [Function],
      "toHaveReturnedWith": [Function],
      "toMatch": [Function],
      "toMatchInlineSnapshot": [Function],
      "toMatchObject": [Function],
      "toMatchSnapshot": [Function],
      "toReturn": [Function],
      "toReturnTimes": [Function],
      "toReturnWith": [Function],
      "toStrictEqual": [Function],
      "toThrow": [Function],
      "toThrowError": [Function],
      "toThrowErrorMatchingInlineSnapshot": [Function],
      "toThrowErrorMatchingSnapshot": [Function],
    }
  `);

  expect(keys).toContain("MongoClient");

  expect(keys).toMatchInlineSnapshot(`
    Array [
      "Binary",
      "BSONRegExp",
      "BSONSymbol",
      "Code",
      "DBRef",
      "Decimal128",
      "Double",
      "Int32",
      "Long",
      "Map",
      "MaxKey",
      "MinKey",
      "ObjectId",
      "Timestamp",
      "ObjectID",
      "MongoBulkWriteError",
      "MongoAPIError",
      "MongoBatchReExecutionError",
      "MongoChangeStreamError",
      "MongoCompatibilityError",
      "MongoCursorExhaustedError",
      "MongoCursorInUseError",
      "MongoDecompressionError",
      "MongoDriverError",
      "MongoError",
      "MongoExpiredSessionError",
      "MongoGridFSChunkError",
      "MongoGridFSStreamError",
      "MongoInvalidArgumentError",
      "MongoKerberosError",
      "MongoMissingCredentialsError",
      "MongoMissingDependencyError",
      "MongoNetworkError",
      "MongoNetworkTimeoutError",
      "MongoNotConnectedError",
      "MongoParseError",
      "MongoRuntimeError",
      "MongoServerClosedError",
      "MongoServerError",
      "MongoServerSelectionError",
      "MongoSystemError",
      "MongoTailableCursorError",
      "MongoTopologyClosedError",
      "MongoTransactionError",
      "MongoWriteConcernError",
      "AbstractCursor",
      "Admin",
      "AggregationCursor",
      "CancellationToken",
      "Collection",
      "Db",
      "FindCursor",
      "GridFSBucket",
      "ListCollectionsCursor",
      "ListIndexesCursor",
      "Logger",
      "MongoClient",
      "Promise",
      "BatchType",
      "GSSAPICanonicalizationValue",
      "AuthMechanism",
      "Compressor",
      "CURSOR_FLAGS",
      "AutoEncryptionLoggerLevel",
      "ExplainVerbosity",
      "LoggerLevel",
      "ServerApiVersion",
      "BSONType",
      "ReturnDocument",
      "ProfilingLevel",
      "ReadConcernLevel",
      "ReadPreferenceMode",
      "ServerType",
      "TopologyType",
      "ReadConcern",
      "ReadPreference",
      "WriteConcern",
      "CommandFailedEvent",
      "CommandStartedEvent",
      "CommandSucceededEvent",
      "ConnectionCheckedInEvent",
      "ConnectionCheckedOutEvent",
      "ConnectionCheckOutFailedEvent",
      "ConnectionCheckOutStartedEvent",
      "ConnectionClosedEvent",
      "ConnectionCreatedEvent",
      "ConnectionPoolClearedEvent",
      "ConnectionPoolClosedEvent",
      "ConnectionPoolCreatedEvent",
      "ConnectionPoolMonitoringEvent",
      "ConnectionReadyEvent",
      "ServerClosedEvent",
      "ServerDescriptionChangedEvent",
      "ServerHeartbeatFailedEvent",
      "ServerHeartbeatStartedEvent",
      "ServerHeartbeatSucceededEvent",
      "ServerOpeningEvent",
      "TopologyClosedEvent",
      "TopologyDescriptionChangedEvent",
      "TopologyOpeningEvent",
      "SrvPollingEvent",
    ]
  `);
});
